jobs:
  include:
    - os: linux
      language: python
      python:
       - "3.8"
      arch: amd64
      dist: focal
      env:
        - secure: "vx7Ow7i7O0ZjAqojO0HgKZr3nehqKvS3Uw7mTJ6YiORcS2vd7YngyEO+ncev0w94RM0bIaX/CzEZKjn0cnaaWlzRvmohHmbEx/LkyGMqGPmSHCdw4muuCOaLNAegn62QNUANkTry0mGHzsrmv60M2AKGkT1LysMDKZC0mwSv8XKqol8zoYnztsechxes7od3xEcrU0ub5XT/nhcreLA0KQjlWY6Gh2SB2l9GHgfmR+uaIYdACI/sPGwZSKFLTaXNsf9zesGoBM4R+rDWb3o5LCm5NMA5SfAFaPG/pHa5HwQNPL2fXArpA/hwnWgqGPJxBY4uGfKd8XGd9kIYhG9EeFuxBNGbohSmqdOll/DlhnjaGVyfteC/4xh3GQTFb8mxJ/xJbEU6jD+KBgaA91ybs8J/vHQlyCqCjzE9AmMfAwZqVSq1e5jedTIlW73SXpE22s1xJRNi1oHExQ+ZtpMaoFZQeKlhk9djcWsax26CwJF1BnJcgW8B36NNRnLylj+qqa9v75Jt9if+KtQR+HCyzisyBJX+5U2ZDsIoMS1goTuQzxigkEUlfq17/DR93Qv5aZpN49+as+nuqpsg+Ruq3K5oC2xBwFb0OQA4yU6lm9nwiFjiqEVM7Siv4Kqp0MN7fC5meSih/EWhnaxQlRi9IArVF/XTZ465sHnOvC0kBIw="
      script:
        - python hello_world.py
