jobs:
  include:
    - os: linux
      language: python
      python:
       - "3.8"
      arch: amd64
      dist: focal
      env:
        - secure: "q8H8Lsh20Q0mITBDAgPK4SMnLN9HG5kmvQisz0nYboKTDjuD3DNGf7F/HZS+648QTjnFTCS072dhbUBcZ+zxn8k5HpQFxaLm2tiPEHZRcyicdYnoTt8DG6cOUbhfofFWzCeALzkDmiqwqsASB/FvVrdqoF0M2Jlnh0Bfp75s/YcLFIAs2mAwjhjPGdXKXag8v/GUwYjJRiJ9neUTHXu2NTUqCE2VSx0tnYOLr5zxtevhcdzhRRFQg31O8tFcWsEW+wvjdf/x6Tl2nCI8v35t26dt3rOu7QZwtjX2zwdtkkLNmE04tS4etWEVheJ2wK/Zm/9JVcQdJEH1f/ZSyS2QmUGqafbq3jfx10t+bx7IoMynQDDF4OF7S9GvHYg1WW1bQ1Iye1Adghv9IPZOvcQ9m83SQCXz25YDUnpzwdeLWCZovTkP05C7lK0VCD0gqfW83Kggkn7mLSmHGbfR6GVAJMX5c8Fmvquv8ijHAF/0ZcY0HjHXe6S0rZ9PcyFVS59oRrFAQEw4W9aCXgyggBIeugGIFEaSrqXQADaGvlIaQVFeYREO9nKgeY/eAj6yUS97HfsHssAJwaP4RdRNctSn1uOODpZRoSGAV3xDnP8uNj45jEOlqVpDN0ubDU7MYRAFaqIN87joKYGMBahJS1pZsX2gp7UIWM5mwGecejvAoKA="
      script:
        - python hello_world.py
